// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnE1F1QUYkASNlBvJaCoxi6OPH6lXr5HQ',
    appId: '1:205744027186:web:bb7072953f541af28d2e2b',
    messagingSenderId: '205744027186',
    projectId: 'full-stack-app-dev-rupp',
    authDomain: 'full-stack-app-dev-rupp.firebaseapp.com',
    storageBucket: 'full-stack-app-dev-rupp.firebasestorage.app',
    measurementId: 'G-RVXNBXLJGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyu2hglsIrrexYi1E-Y0AsF7HnKqsreeo',
    appId: '1:205744027186:android:9d46f6747dd2abc28d2e2b',
    messagingSenderId: '205744027186',
    projectId: 'full-stack-app-dev-rupp',
    storageBucket: 'full-stack-app-dev-rupp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCX1i2wx3haaeRO1d_StXfbplK2MerV8Q',
    appId: '1:205744027186:ios:55366290be27b6c48d2e2b',
    messagingSenderId: '205744027186',
    projectId: 'full-stack-app-dev-rupp',
    storageBucket: 'full-stack-app-dev-rupp.firebasestorage.app',
    iosBundleId: 'com.example.pyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnE1F1QUYkASNlBvJaCoxi6OPH6lXr5HQ',
    appId: '1:205744027186:web:6a107db7bf83b9e38d2e2b',
    messagingSenderId: '205744027186',
    projectId: 'full-stack-app-dev-rupp',
    authDomain: 'full-stack-app-dev-rupp.firebaseapp.com',
    storageBucket: 'full-stack-app-dev-rupp.firebasestorage.app',
    measurementId: 'G-BR2MBGFX6E',
  );
}
